const express = require('express');
const mongoose = require('mongoose');
const cloudinary = require('cloudinary').v2;
const multer = require('multer');
const { CloudinaryStorage } = require('multer-storage-cloudinary');
require('dotenv').config();

const app = express();
app.use(express.json());

// 1. Connect to MongoDB Atlas (Cloud DB)
mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log("Connected to MongoDB Atlas"));

// 2. Configure Cloudinary (Cloud File Storage)
cloudinary.config({
  cloud_name: process.env.CLOUD_NAME,
  api_key: process.env.API_KEY,
  api_secret: process.env.API_SECRET
});

// 3. Setup Multer to send files directly to Cloudinary
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: { folder: 'skill_passports', format: async () => 'pdf' },
});
const upload = multer({ storage: storage });

// 4. Data Model
const Student = mongoose.model('Student', {
  name: String,
  email: String,
  certUrl: String // This will store the Cloudinary Link
});

// 5. API Route: Save to Cloud
app.post('/api/upload-passport', upload.single('certificate'), async (req, res) => {
  const newStudent = new Student({
    name: req.body.name,
    email: req.body.email,
    certUrl: req.file.path // The cloud URL generated by Cloudinary
  });
  await newStudent.save();
  res.json({ message: "Successfully saved to Cloud!", data: newStudent });
});

app.listen(5000, () => console.log("Cloud Server Running"));